# ControlCamera Configuration File
# Minimal configuration with only settings used by the current code

# Model Configuration
model:
  primary_model_path: "/home/circuito/AMT/ControlCamera/ControlCamera/veinmodel.pt"
  classes_file: "/home/circuito/AMT/ControlCamera/ControlCamera/veinclasses.txt"
  confidence_threshold: 0.4 # Lower for better recall

  # GPU/CPU Configuration for RTX 3050 6GB
  # IMPORTANT: Change these settings to use your RTX 3050:
  # 1. Set use_gpu: true
  # 2. Set device: "cuda:0"
  device: "cpu" # Current: CPU mode
  use_gpu: false # Current: GPU disabled

  # To enable RTX 3050 6GB GPU acceleration, change to:
  # device: "cuda:0"
  # use_gpu: true

  # Multi-scale detection settings
  multi_scale_detection: true
  scales: [0.8, 1.0, 1.2]
  nms_iou_threshold: 0.4

# Camera Configuration - Using only camera0
camera:
  port: 0 # Use /dev/video0

  # Camera settings optimized for vein detection
  settings:
    auto_exposure: false
    auto_white_balance: false
    brightness: 85 # Slightly higher for better vein contrast
    contrast: 45 # Increased contrast
    exposure: -3 # Lower exposure for NIR
    gain: 40 # Higher gain for NIR sensitivity
    saturation: 10 # Lower saturation for NIR
    sharpness: 28 # Higher sharpness for vein details
    white_balance: 3800 # Optimized for NIR wavelength

# Image Processing Configuration
image_processing:
  # CLAHE (Contrast Limited Adaptive Histogram Equalization) - Optimized for veins
  clahe:
    enabled: true
    clip_limit: 4.0 # Higher clip limit for better vein enhancement
    tile_grid_size_x: 6 # Smaller tiles for more local enhancement
    tile_grid_size_y: 6

  # Image filters for vein enhancement
  filters:
    bilateral:
      enabled: true
      diameter: 9
      sigma_color: 75
      sigma_space: 75

    contrast:
      enabled: true
      alpha: 2.2 # Higher contrast enhancement for better vein visibility
      beta: 15 # Increased brightness offset

    gaussian:
      enabled: true
      kernel_size: 5
      sigma: 1.2

    median:
      enabled: true
      kernel_size: 5

    morphology:
      enabled: true
      operation: "close"
      kernel_size: 3

    adaptive_threshold:
      enabled: true
      block_size: 11
      c_value: 2

    hessian:
      enabled: true
      sigma_values: [0.5, 1.0, 1.5, 2.0, 3.0, 4.0] # More scales for better vessel detection

    # Advanced vein enhancement settings
    advanced_enhancement:
      enabled: true
      directional_filters: true
      top_hat_enhancement: true
      multi_scale_vessel_enhancement: true
