# ControlCamera Configuration File
# Minimal configuration with only settings used by the current code

# Model Configuration
model:
  primary_model_path: "/home/circuito/AMT/ControlCamera/ControlCamera/veinmodel.pt"
  classes_file: "/home/circuito/AMT/ControlCamera/ControlCamera/veinclasses.txt"
  confidence_threshold: 0.5

# Camera Configuration - Using only camera0
camera:
  port: 0 # Use /dev/video0

  # Camera settings for vein detection
  settings:
    auto_exposure: false
    auto_white_balance: false
    brightness: 80
    contrast: 40
    exposure: -2
    gain: 32
    saturation: 16
    sharpness: 24
    white_balance: 4000

# Image Processing Configuration
image_processing:
  # CLAHE (Contrast Limited Adaptive Histogram Equalization)
  clahe:
    enabled: true
    clip_limit: 3.0
    tile_grid_size_x: 8
    tile_grid_size_y: 8

  # Image filters for vein enhancement
  filters:
    bilateral:
      enabled: true
      diameter: 9
      sigma_color: 75
      sigma_space: 75

    contrast:
      enabled: true
      alpha: 1.8
      beta: 10

    gaussian:
      enabled: true
      kernel_size: 5
      sigma: 1.2

    median:
      enabled: true
      kernel_size: 5

    morphology:
      enabled: true
      operation: "close"
      kernel_size: 3

    adaptive_threshold:
      enabled: true
      block_size: 11
      c_value: 2

    hessian:
      enabled: true
      sigma_values: [1.0, 2.0, 3.0, 4.0]
